project:
  type: website
  resources:
    - images/
    - assets/
    - robots.txt

website:
  favicon: /images/favicon.png
  twitter-card: true
  title: "
    <span class='hidden'>DTN Lisbon 2025</span>
    <img class='header-logo' src='/images/logos/dtn_lisbon.png' alt='EIT Urban Mobility DTN Annual Forum 2025' />
    "
  image: "/images/backgrounds/dtn.png"
  site-url: https://www.dtnlisbon.pt
  search: true
  navbar:
    pinned: false
    background: white
    left:
      - href: index.qmd
        text: Home
      - sidebar:info
      - sidebar:contacts
      - sidebar:program
      - sidebar:courses

  sidebar:
    - id: program
      title: "Forum"
      collapse-level: 2
      contents:
        - forum/day1.qmd
        - forum/day2.qmd
        - forum/day3.qmd
        - forum/technical.qmd
        - forum/pitches.qmd
        - forum/lisbon.qmd
        - speakers/index.qmd
    - id: courses
      title: "Courses"
      collapse-level: 2
      contents:
        - courses/course1.qmd
        - courses/course2.qmd
        - courses/course3.qmd
        - speakers/courses.qmd
    - id: info
      title: "Practical info"
      collapse-level: 2
      contents:
        - info/venue.qmd
        - info/gettingHere.qmd
        - info/gettingAround.qmd
        - info/gettingToLisbon.qmd
        - info/accommodation.qmd
        - info/guides.qmd
    - id: contacts
      title: "Contacts"
      collapse-level: 2
      contents:
        - info/team.qmd
        - info/contacts.qmd
    - id: speakers
      title: "Speakers"
      collapse-level: 2
      contents:
        - speakers/index.qmd
        - speakers/jcosteira.qmd
        - speakers/zbent.qmd
        - speakers/hhook.qmd
        - speakers/dvale.qmd
        - speakers/mpoyourow.qmd
        - speakers/mcosta.qmd
        - speakers/kclifton.qmd
    - id: instructors
      title: "Course instructors"
      collapse-level: 2
      contents:
        - speakers/courses.qmd
        - speakers/amonzon.qmd
        - speakers/rlovelace.qmd
        - speakers/hhook.qmd

  page-footer:
    left: "
      <a href='https://www.ulisboa.pt/en' target='_blank'><img class='footer-ulisboa' src='/images/logos/ulisboa.png' /></a>
      <a href='https://tecnico.ulisboa.pt/en/' target='_blank'><img class='footer-ulisboa' src='/images/logos/ist.png' /></a>
      <a href='https://www.igot.ulisboa.pt/' target='_blank'><img class='footer-igot' src='/images/logos/igot.png' /></a>
      <a href='https://www.eiturbanmobility.eu/' target='_blank'><img class='footer-eit'src='/images/logos/eit.png' /></a>
      "
    right:
      - icon: github
        href: https://github.com/U-Shift/dtn25




format:
  html:
    theme:
    - default
    - styles/theme.scss
    mainfont: Titillium web
    css: styles.css
    toc: false
    include-after-body: scripts/global.html
    include-in-header: scripts/robots.html


editor: visual

