project:
  type: website
  resources:
    - images/

website:
  title: "DTN Annual Forum 2025"
  search: false
  navbar:
    pinned: false
    background: white
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sidebar:program
      - sidebar:courses

  sidebar:
    - id: program
      title: "Forum"
      collapse-level: 2
      contents: 
        - forum/day1.qmd
        - forum/day2.qmd
        - forum/day3.qmd
    - id: courses
      title: "Courses"
      collapse-level: 2
      contents:
        - courses/course1.qmd
        - courses/course2.qmd
        - courses/course3.qmd
        - courses/course4.qmd

  page-footer: 
    left: "
      <img src='/images/logos/ulisboa.png' style='width:10%; margin-right: 1rem;' />

      <img src='/images/logos/eit.png' style='width:50%;' />
    " 
    right: 
      - icon: github
        href: https://github.com/U-Shift/dtn25


    

format:
  html:
    theme: 
    - default
    - styles/theme.scss
    mainfont: Titillium web
    css: styles.css
    toc: false


editor: visual

