project:
  type: website

website:
  title: "DTN Annual Forum 2025"
  search: false
  navbar:
    pinned: true
    background: transparent
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sidebar:program

  sidebar:
    - id: program
      title: "Program"
      collapse-level: 2
      contents: 
        - program/day1.qmd
        - program/day2.qmd
        - program/day3.qmd

  page-footer: 
    left: "
      <img src='/images/logos/ulisboa.png' style='width:10%; margin-right: 1rem;' />
      <img src='/images/logos/eit.png' style='width:50%;' />
    " 
    right: 
      - icon: github
        href: https://github.com/U-Shift/dtn25


    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

