---
title: Kelly Clifton
image: https://lh5.googleusercontent.com/proxy/eQNqQwgDO1a1rLkSMsvKt6jaIofFwxWDtDqQhZDGw2VMM_6chpT51vz8Vb0Hr8lngmUVG99_Ebk3O7Yz4n_t0nFrnW1Kzhlv-zSS9VmDuLHm0SMh
about:
    template: trestles

# FROM https://scarp.ubc.ca/directory/kelly-j-clifton
---

Kelly J. Clifton is a professor at the **University of British Columbia**, Canada, and an internationally-recognized expert on 
transport and land use interactions, travel behaviour, 
pedestrian modeling, and equity in transportation policy. She has worked to elevate public impact research through 
partnerships with public agencies and community groups. Previously, Kelly was Professor of **Portland State University’s**
Civil and Environmental Engineering, an affiliate of the Urban Studies and Planning Program, and a Fellow in the 
**Institute for Sustainable Solutions**. In addition to her faculty appointments there, she served as the interim 
Associate Vice President for Research for the campus and was the former Associate Dean of Research for the 
**Maseeh College of Engineering and Computer Science**. She has also held faculty positions at the **University of Maryland**
and **University of Iowa**. Kelly has a PhD in Community and Regional Planning from the **University of Texas** at Austin, MS 
in Planning from the **University of Arizona**, and BS in Mechanical Engineering from **West Virginia University**. 

<div class="alert alert-light">{{< fa calendar >}} This speaker will host a keynote on the [12th September](/forum/day3.html)</div>
