---
title: Pitch & poster instructions
format:
  html:
    css: ../styles/schedule.css
---

<div class="alert alert-light">
  {{< fa calendar >}} This page refers to an event that will take place on the [10th September](/forum/day1.html)
</div>

As part of this year’s forum, some attendees will present a brief overview of their research. 
Please follow the instructions below to prepare your contribution.

<br/>


## 🔹 3-Minute Research Pitch

**Prepare a 3-minute presentation** highlighting your current or previous research.

> You may use slides to support your pitch (PowerPoint or PDF format).
> Slides will be loaded in advance, so please do not plan to use your own laptop.

📌 **Important!**

**Pitching is mandatory for all DTN members who have not presented in previous editions.**
If you have already pitched in a past forum, you are still very welcome to present again if you would like to share updates or new research.

## 🔹 A1 Poster (Landscape Orientation)

**Design a poster (A1 size, landscape format) that visually communicates your research.**

> Be creative! The layout and content are up to you.

**Mandatory:** Please use the [this](https://docs.google.com/presentation/d/1eqFZmfMZIBVxsZq9QJ1qSoJLB1ofPobw/edit?usp=sharing&ouid=105732216854601135740&rtpof=true&sd=true){target=_blank} template.


## 📤 Submission

**Deadline:** August 25

<br/> 

**To ensure a smooth setup and free printing** of your poster, please submit both your slides and poster by email to: ✉️ [mauricio.orozco@tecnico.ulisboa.pt](mailto:mauricio.orozco@tecnico.ulisboa.pt)


<br/>

**⚠️ Late submissions will not be printed, so please respect the deadline.**

<br/>

**All posters will be displayed throughout the 3-day event — make yours stand out!**